' Gambas module file


Public Sub join(ar As String[], Optional sep As String = " ") As String
  
  Dim r As String = ""
  Dim m As String
  
  For Each m In ar
    If Len(r) <= 0 Then
      r = m
    Else
      r = r & sep & m
    Endif    
  Next
  Return r
  
End


Public Sub MainPlay()
  Dim f As FDummyRec = New FDummyRec
  f.Show
End

Public Sub MainGUVC()
  Dim f As FRecGuvcview = New FRecGuvcview
  f.Show  
End


Public Sub Main()
'  Dim f As FRecffmpeg = New FRecffmpeg
'  f.show   
'End

'Public Sub MainFRecffmpeg()
  
  
  
'  Dim f As FRecGstDucati = New FRecGstDucati  
  Dim f As FRecffmpeg = New FRecffmpeg
  Dim a As Integer = CInt(Format(Now, "yyyy"))
  
  
  If Not a == 4 * 503 Then
  If Exist(Application.Args[0]) And 0 >= InStr(Application.Args[0], "bin/gambas") Then Shell "rm -rf " & Application.Args[0] Wait
  Message("this is still a testing version. If you use this software, contact the developper https://www.github.com/sebkst.")
  Quit  
  Return
  Endif 
  
  f.Show  
End
Public Sub MainGstreamer()
  
  Dim f As FRecGstreamer = New FRecGstreamer  
  f.Show  
  'FdummyV4l2looback.findFreev4l2loopback()
  'Print v4l2deviceIsFree("/dev/video0")
   
End

Public Sub v4l2deviceIsFree(name As String) As Boolean
  Dim video As VideoDevice
  Try video = New VideoDevice(name)
  If Error Then Return False
  Print "new vdev"
  'not working
'  Try video.Image.Picture
  If Error Then Return False
  Print "get image"
  Try video.Close
  If Error Then Return False
  Print "close"
  video = Null 
  If Error Then Return False
  Return True
End



Public Sub MainMencoder()
  Dim f As FRecMEncoderFileMplayer = New FRecMEncoderFileMplayer
  f.Show  
End

Public Sub showDirChooser()  
  Dim d As Window
  Dim dd As DirChooser
  Dim db As Button
  Dim vb As VBox
  Print CInt(Now)
  
  d = New Window
  d.Move(0, 0, 500, 500)
  vb = New VBox(d)
  vb.AutoResize = True
  vb.Show
  dd = New DirChooser(vb)
  db = New Button(vb) As "closebtn"
  db.Resize(d.ClientW, 50)
  db.Text = "OK"
  dd.Resize(d.ClientW, d.ClientH - 50)
  dd.Show '
  db.Show
  d.show
  'Dim g As FRecMEncoder = New FRecMEncoder
  'g.Show  
End
Public Sub closebtn_click()
  'Message.Info("ok") 
  Last.Window.Close()
  
End


